name: Bright

on:
  pull_request:
    branches:
      - '*'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install SecTester dependencies
        run: npm i --save=false --prefix .brightsec @sectester/core @sectester/repeater @sectester/scan @sectester/runner @sectester/reporter

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_sqlite, gd, intl, zip, imagick
          coverage: none

      - name: Install dependencies
        run: |
          apk update && \
          apk add --no-cache shadow sqlite-dev libpng libpng-dev libjpeg-turbo libjpeg-turbo-dev freetype freetype-dev curl autoconf libgomp icu-dev icu-data-full nginx dcron tzdata imagemagick imagemagick-dev libzip-dev sqlite libwebp-dev && \
          docker-php-ext-install pdo pdo_sqlite calendar && \
          docker-php-ext-enable pdo pdo_sqlite && \
          docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && \
          docker-php-ext-install -j$(nproc) gd intl zip && \
          pecl install imagick && \
          docker-php-ext-enable imagick

      - name: Build Docker image
        run: docker build -t wallos .

      - name: Run Docker container
        run: docker run -d -p 8282:80 --name wallos -e TZ=America/Toronto wallos

      - name: Wait for application to be ready
        run: |
          for i in {1..30}; do
            nc -zv 127.0.0.1 8282 && echo "Application is ready" && exit 0
            echo "Waiting for application..."
            sleep 5
          done
          echo "Application did not start in time" && exit 1

      - name: Configure Bright credentials
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: dzZUZGaqqVhvHnZnjfXUoP
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: dzZUZGaqqVhvHnZnjfXUoP
          BRIGHT_AUTH_ID: ${{ vars.BRIGHT_AUTH_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:8282
        run: node --experimental-transform-types --experimental-strip-types --experimental-detect-module --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning --test-force-exit --test-concurrency=4 --test .brightsec/tests/*.test.ts

      - name: Clean up
        run: docker stop wallos && docker rm wallos
